// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

using Amazon.CDK.AWS.Lambda;

namespace Aspire.Hosting.AWS.Lambda;

/// <summary>
/// Options that can be added to the Lambda function resource.
/// </summary>
public class LambdaFunctionOptions
{
    /// <summary>
    /// The format for the log messages generated by the Lambda function. Default format is Text.
    /// </summary>
    public Amazon.Lambda.LogFormat LogFormat { get; set; } = Amazon.Lambda.LogFormat.Text;

    /// <summary>
    /// The minimum log level captured from the Lambda function. Default log level is INFO.
    /// </summary>
    public Amazon.Lambda.ApplicationLogLevel ApplicationLogLevel { get; set; } = Amazon.Lambda.ApplicationLogLevel.INFO;
}
