// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

namespace Aspire.Hosting.AWS.Lambda;

/// <summary>
/// TypeScript/node friendly version of <see cref="LambdaFunctionOptions"/> used only by the polyglot AppHost.
/// The properties are plain strings because the AWS SDK types used by <see cref="LambdaFunctionOptions"/>
/// (Amazon.Lambda.LogFormat and Amazon.Lambda.ApplicationLogLevel) are not representable in a language neutral DTO.
/// This type is internal so .NET AppHosts continue to use <see cref="LambdaFunctionOptions"/> while only the
/// generated TypeScript SDK sees this shape.
/// </summary>
[AspireDto]
internal sealed class LambdaFunctionPolyglotOptions
{
    /// <summary>
    /// The format for the log messages generated by the Lambda function, for example "Text" or "Json". Default format is Text.
    /// </summary>
    public string? LogFormat { get; set; }

    /// <summary>
    /// The minimum log level captured from the Lambda function, for example "TRACE", "DEBUG", "INFO", "WARN", "ERROR" or "FATAL".
    /// Default log level is INFO.
    /// </summary>
    public string? ApplicationLogLevel { get; set; }
}
