permissions:
  contents: write
  id-token: write
"on":
  pull_request:
    types:
    - closed
name: Sync 'dev' and 'main'
jobs:
  clean-up-closed-release:
    if: |
      github.event.pull_request.merged == false &&
      github.event.pull_request.head.ref == 'releases/next-release' &&
      github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    name: Clean up closed release
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      name: Checkout code
      with:
        ref: releases/next-release
        fetch-depth: 0
    - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
      name: Setup .NET 9.0
      with:
        dotnet-version: 9.0.x
    - run: dotnet tool install --global AutoVer --version 0.0.24
      name: Install AutoVer
    - run: |
        git config --global user.email "github-aws-sdk-dotnet-automation@amazon.com"
        git config --global user.name "aws-sdk-dotnet-automation"
      name: Setup Git User
    - run: |
        tag=$(autover changelog --tag-name)
        echo "TAG=$tag" >> $GITHUB_OUTPUT
      id: read-tag-name
      name: Read Tag Name
    - run: |
        git fetch origin
        git push --delete origin ${{ steps.read-tag-name.outputs.TAG }}
        git push origin --delete releases/next-release
      name: Clean up
  sync-dev-and-main:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'releases/next-release' &&
      github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    name: Sync dev and main
    steps:
    - uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
      name: Configure AWS Credentials
      with:
        aws-region: us-west-2
        role-to-assume: ${{ secrets.RELEASE_WORKFLOW_ACCESS_TOKEN_ROLE_ARN }}
    - uses: aws-actions/aws-secretsmanager-get-secrets@5e19ff380d035695bdd56bbad320ca535c9063f2
      name: Retrieve secret from AWS Secrets Manager
      with:
        parse-json-secrets: true
        secret-ids: |
          AWS_SECRET, ${{ secrets.RELEASE_WORKFLOW_ACCESS_TOKEN_NAME }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      name: Checkout code
      with:
        ref: dev
        fetch-depth: 0
        token: ${{ env.AWS_SECRET_TOKEN }}
    - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
      name: Setup .NET 9.0
      with:
        dotnet-version: 9.0.x
    - run: dotnet tool install --global AutoVer --version 0.0.24
      name: Install AutoVer
    - run: |
        git config --global user.email "github-aws-sdk-dotnet-automation@amazon.com"
        git config --global user.name "aws-sdk-dotnet-automation"
      name: Setup Git User
    - run: |
        version=$(autover changelog --release-name)
        echo "VERSION=$version" >> $GITHUB_OUTPUT
      id: read-release-name
      name: Read Release Name
    - run: |
        tag=$(autover changelog --tag-name)
        echo "TAG=$tag" >> $GITHUB_OUTPUT
      id: read-tag-name
      name: Read Tag Name
    - run: |
        changelog=$(autover changelog --output-to-console)
        echo "CHANGELOG<<EOF"$'\n'"$changelog"$'\n'EOF >> "$GITHUB_OUTPUT"
      id: read-changelog
      name: Read Changelog
    - run: |
        git fetch origin
        git checkout main
        git merge dev
        git push origin main
      name: Merge dev to main
    - run: |
        gh release create "${{ steps.read-tag-name.outputs.TAG }}" --title "${{ steps.read-release-name.outputs.VERSION }}" --notes "${{ steps.read-changelog.outputs.CHANGELOG }}"
      env:
        GITHUB_TOKEN: ${{ env.AWS_SECRET_TOKEN }}
      name: Create GitHub Release
    - run: |
        git fetch origin
        git push origin --delete releases/next-release
      name: Clean up
